---
title: "Wolf CSSE Plots"
author: "RB"
date: "2024-05-15"
output: html_document
---

## R Markdown

####


```{r}
libs <- c('data.table', 'readr', 'dplyr', 'lubridate', 'tidyr', 'ggplot2','stringr', 'tibble', 'patchwork', 'performance','see','viridis','skimr', 'janitor','tidyverse', 'naniar', 'knitr')
lapply(libs, require, character.only = TRUE)

```


###Load data
```{r}
dat <- read_csv("~/Github/preyswitch_litrev/data/WolfDataExtraction_PreyPref.csv")
```

#dat <- read_csv('data/WolfDataExtraction_PreyPref.csv') ###tibble version



###Any data transformation or cleaning needed

#####Plots


```{r}
pref.plot1 <- ggplot(dat) +
  geom_point(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, col = Livestock_Wild)) + ##or col = Paper_ID
  geom_abline(intercept = 0, slope = 1, linetype="dashed") + ###constant 1:1 line
  theme_classic() + theme(text = element_text(size = 15)) +
  scale_colour_viridis(option= "inferno",discrete = TRUE, end = .9, na.translate = F) +
  xlab("Biomass Available") + ylab("Biomass Consumed") +
  labs(colour="Prey Category")
pref.plot1
ggsave("plots/wolf-pref-live.wild_inferno.png", 
       height = 5, width = 7, dpi = 700)
```

```{r}
pref.plot4 <- ggplot(dat) +
  geom_point(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed,col= Mass_Cat_A))+   ##or col = Paper_ID 
  #geom_line(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, group=Paper_ID))+#if we wanna check by Paper_ID
  geom_abline(intercept = 0, slope = 1, linetype="dashed") + ###constant 1:1 line
  theme_classic() + theme(text = element_text(size = 15)) +
  scale_colour_viridis(option="inferno",discrete = TRUE, end = .9, na.translate = F) +
  xlab("Biomass Available") + ylab("Biomass Consumed") +
  labs(colour="Mass Category")
pref.plot4
ggsave("plots/wolf-preference-MassCategories_inferno.png", 
       height = 5, width = 7, dpi=700)
```


```{r}
pref.plot2 <- ggplot(dat) +
  geom_point(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, col=cut(Avg_Mass_kg,quantile(Avg_Mass_kg, na.rm = TRUE)))) + ##or col = Paper_ID 
  #geom_line(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, group=Paper_ID))+#if we wanna check by Paper_ID
  geom_abline(intercept = 0, slope = 1, linetype="dashed") + ###constant 1:1 line
  theme_classic() + theme(text = element_text(size = 12)) +
  scale_colour_viridis(discrete = TRUE, end = .9, na.translate = F) +
  xlab("Biomass Available") + ylab("Biomass Consumed") +
  labs(colour="Mass") 
pref.plot2
ggsave("plots/wolf-preference-mass.png", 
       height = 5, width = 7)
```


```{r}
pref.plot3 <- ggplot(dat) +
  geom_point(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, col=Paper_ID)) + ##or col = Paper_ID 
  #geom_line(aes(x = Prop_BM_Avail, y = Prop_BM_Consumed, group=Paper_ID))+#if we wanna check by Paper_ID
  geom_abline(intercept = 0, slope = 1, linetype="dashed") + ###constant 1:1 line
  theme_classic() + theme(text = element_text(size = 12)) +
  scale_colour_viridis(discrete = TRUE, end = .9, na.translate = F) +
  xlab("Biomass Available") + ylab("Biomass Consumed") +
  labs(colour="Paper")
pref.plot3
ggsave("plots/wolf-preference-Paper_ID.png", 
       height = 5, width = 7)
```

```{r}
dat %>%
  skim_without_charts() ### add one cuz one horse is domestic one is feral/wild
```
```{r}
pref <- dat %>%
  group_by(Livestock_Wild) %>%
  summarise(
  "positive" = filter(BM_Use > 1))
pref

```
```{r}
help <- dat %>%
  group_by(Livestock_Wild)%>%
  filter(BM_Use>1)
help
help2 <- dat %>%
  group_by(Livestock_Wild)%>%
  filter(BM_Use<1)
help2
```

```{r}
preference.table <- dat %>%
  group_by(Livestock_Wild) %>%
  summarise(
    "Positive" = list(BM_Use>1),
    "Negative" = list(BM_Use<1)) 
preference.table
```
