---
title: "GLMM"
author: "RB"
date: "2025-11-04"
output: html_document
---


```{r}
libs <- c('Matrix','lme4','glmmTMB', 'ggeffects','data.table', 'readr', 'dplyr', 'lubridate', 'tidyr', 'ggplot2','stringr', 'tibble', 'patchwork', 'performance','see','viridis','skimr', 'janitor','tidyverse', 'naniar', 'knitr', 'broom')
lapply(libs, require, character.only = TRUE)
```

```{r}
ScatPref_Nov2025 <- read_csv("~/WIP - Report Stage 2/data/ScatPref_Nov2025.csv")
StudyArea_Nov2025 <- read_csv("~/WIP - Report Stage 2/data/StudyArea_Nov2025.csv")
```


```{r}
scatpref.unfinished <- ScatPref_Nov2025 %>%
  select(Study_Code, Paper_ID, Study_Area, Area, Prey_Item, Prey_Taxa_Valid, Period, Num_Ind, Ratio_Ind_Avail, Prop_Ind_Avail, Density, Avg_Mass_kg, Pantheria_kg, Orig_BM_Avail, Orig_Prop_BM_Avail, Scat_n_Tot, Scat_n_Prey, Abs_FO, Rel_FO, Mean_Perc_Vol, Orig_BM_Consumed, Orig_Prop_BM_Consumed, Livestock_Wild, Defense, n_Prey_Species, Wild_Ung_Avail_n) %>%
  filter(!Study_Code %in% ("DAS12ADC")) %>%
    filter(!(Study_Code == "VAE09HNP" & Prey_Item == "Hare")) %>%
  filter(!Livestock_Wild %in%c("Feral", "Livestock")) %>%
  group_by(Study_Code, Period) %>%
  filter(n() >= 2) %>%
  ungroup() %>%
   mutate(
    Prey_Taxa_Valid = if_else(
      Prey_Taxa_Valid == "Alces americanus",
      "Alces alces",
      Prey_Taxa_Valid
    )
  )

#need to remove Chavez 2005 1997-1999 Spring-Autumn
#davis 2012 needs to be removed
#Gazzola 2007 needs to be dealt with


studyarea <- StudyArea_Nov2025 %>%
  mutate(Realm_Olson = ifelse(is.na(Realm_Olson), "NA", Realm_Olson),
 Suprarealm_OneEarth = ifelse(is.na(Suprarealm_OneEarth), "NA", Suprarealm_OneEarth),
 Biome_Detal_Name = case_when(
    Biome_Detal_Name == "Temperate Broadleaf & Mixed Forests" ~ "TempBroadMixFor",
    Biome_Detal_Name == "Temperate Grasslands, Savannas & Shrublands" ~ "TempGrassSavShrub",
    Biome_Detal_Name == "Boreal Forests/Taiga" ~ "BorealForestTaiga",
    Biome_Detal_Name == "Mediterranean Forests, Woodlands & Scrub" ~ "MediForScrub",
    Biome_Detal_Name == "Temperate Conifer Forests" ~ "TempConiferFor",
    Biome_Detal_Name == "Montane Grasslands & Shrublands" ~ "MontGrassShrub",
    Biome_Detal_Name == "Tundra" ~ "Tundra",
    Biome_Detal_Name == "Deserts & Xeric Shrublands" ~ "DesertXericShrub",
    TRUE ~ Biome_Detal_Name
  )) %>%
  select(Study_Code, Study_Country, Realm_Olson, Realm_OneEarth, Biome_Olson, Biome_Detal, Biome_Detal_Name, Bioregion_Olson, Bioregion_OneEarth, Eco_Code_Olson, Eco_Num_Olson, Ecoregion_Olson, Suprarealm_OneEarth, Subrealm_OneEarth, Ecoregion_OneEarth, Ecoregion_OneEarth2)

scatstudy.unfinished <- scatpref.unfinished %>%
  left_join(studyarea, by = "Study_Code")

scatstudy.unfinished$Mass_Cat <- cut(scatstudy.unfinished$Pantheria_kg,
                                     breaks = c(0, 20.5, 80.5, 150.5, 300.5, 500.5, Inf),  
                                     labels = c("≤ 20 kg", "20-80 kg", "80-150 kg", "150-300 kg", "300-500 kg", "≥ 500 kg"), 
                                     right = FALSE) # Use right=FALSE for inclusive lower bounds


scatstudy.unfinished <- scatstudy.unfinished %>%
   mutate(
   Area = as.numeric(Area),
   Prop_Ind_Avail = as.numeric(Prop_Ind_Avail),
   Num_Ind = as.numeric(Num_Ind),
   Density = as.numeric(Density),
    Pantheria_kg = as.numeric(Pantheria_kg),
    Mass_Cat = as.factor(Mass_Cat),
    Study_Code = as.factor(Study_Code),
    Prey_Taxa_Valid = as.factor(Prey_Taxa_Valid),
    Scat_n_Prey = as.numeric(Scat_n_Prey),
    Scat_n_Tot = as.numeric(Scat_n_Tot),
    Abs_FO = as.numeric(Abs_FO),
    Rel_FO = as.numeric(Rel_FO),
   Defense = as.factor(Defense),
   n_Prey_Species = as.numeric(n_Prey_Species),
   Wild_Ung_Avail_n = as.numeric(Wild_Ung_Avail_n),
   Study_Code = as.factor(Study_Code),
   Study_Country = as.factor(Study_Country),
  Realm_Olson = as.factor(Realm_Olson),
  Realm_OneEarth = as.factor(Realm_OneEarth),
  Biome_Olson = as.factor(Biome_Olson),
  Biome_Detal = as.factor(Biome_Detal),
  Biome_Detal_Name = as.factor(Biome_Detal_Name),
  Bioregion_Olson = as.factor(Bioregion_Olson),
  Bioregion_OneEarth = as.factor(Bioregion_OneEarth),
  Eco_Code_Olson = as.factor(Eco_Code_Olson),
  Eco_Num_Olson = as.factor(Eco_Num_Olson),
  Ecoregion_Olson = as.factor(Ecoregion_Olson),
  Ecoregion_OneEarth = as.factor(Ecoregion_OneEarth),
  Ecoregion_OneEarth2 = as.factor(Ecoregion_OneEarth2),
  Suprarealm_OneEarth = as.factor(Suprarealm_OneEarth),
  Subrealm_OneEarth = as.factor(Subrealm_OneEarth)
   )

skim_without_charts(scatstudy.unfinished)
```

```{r}
unique(studyarea$Study_Country)
```


```{r}
scatstudy <- scatstudy.unfinished %>%
  mutate(Num_Ind = if_else(is.na(Num_Ind) & !is.na(Density) & !is.na(Area),
                            Density * Area, Num_Ind)) %>% 
  mutate(Density = if_else(is.na(Density) & !is.na(Num_Ind) & !is.na(Area),
                           Num_Ind / Area, Density)) %>%
group_by(Study_Code, Period) %>%
   mutate(Ind_Tot = sum(Num_Ind),
    Density_Tot = sum(Density),
    Prop_Ind_Avail_Sum = sum(Prop_Ind_Avail)) %>%
  ungroup() %>%
          # Proportion of individuals available
         mutate(Prop_Ind = case_when(
      is.na(Num_Ind) & !is.na(Prop_Ind_Avail) ~ Prop_Ind_Avail/Prop_Ind_Avail_Sum,
      !is.na(Num_Ind) & !is.na(Ind_Tot) ~ Num_Ind / Ind_Tot,
      !is.na(Density) & !is.na(Density_Tot) ~  Density / Density_Tot,
      TRUE ~ NA_real_
    ),
         # Ratio of individuals available
           Pre_Ratio_Ind = 1 - Prop_Ind,
    Ratio_Ind = Prop_Ind / Pre_Ratio_Ind,
  ) %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
 # Proportion of Pantheria kg available
   mutate(PropInd_x_Pan = Prop_Ind * Pantheria_kg) %>%
  ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Sum_PropInd_x_Pan = sum(PropInd_x_Pan)) %>%
  mutate(Prop_kg_Avail = PropInd_x_Pan / Sum_PropInd_x_Pan) %>%
 # Ratio of Pantheria kg available
  mutate(Pre_Ratio_kg_Avail = Sum_PropInd_x_Pan - PropInd_x_Pan) %>%
  mutate(Ratio_kg_Avail = PropInd_x_Pan / Pre_Ratio_kg_Avail) %>%
  #Step 2: Calculate the Scat_n_Prey, new relative FO, BM consumed, and ratio and prop of BM consumed
  #Make sure everything has a Scat_n_Prey if possible
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(Scat_n_Prey = ifelse(is.na(Scat_n_Prey), Scat_n_Tot*Abs_FO/100, Scat_n_Prey)) %>%
  ungroup() %>%
  #Calculate a new Relative_FO and a Ratio of Occurences
   group_by(Study_Code, Period) %>%
   mutate(Scat_items_Tot = sum(Scat_n_Prey)) %>%
    mutate(New_Rel_FO = Scat_n_Prey/Scat_items_Tot) %>%
    mutate(Pre_Ratio_Occ = Scat_items_Tot - Scat_n_Prey) %>%
    mutate(Ratio_Occs = Scat_n_Prey/Pre_Ratio_Occ) %>%
  #Calculate BM consumed (using (kg per scat)*Abs FO = 0.439+(0.008*Pan kg))
  mutate(Abs_FO = ifelse(is.na(Abs_FO), Scat_n_Prey/Scat_n_Tot, Abs_FO)) %>%
   mutate(kg_Per_Scat = 0.439+0.008*Pantheria_kg) %>%
#Calculate the proportion and ratio of biomass consumed
  mutate(Prey_Tot_kg_Cons = kg_Per_Scat*Scat_n_Prey) %>%
  mutate(Tot_kg_Cons = sum(Prey_Tot_kg_Cons)) %>%
  mutate(Prop_kg_Cons = Prey_Tot_kg_Cons/Tot_kg_Cons) %>%
  mutate(Pre_Ratio_kg_Cons = Tot_kg_Cons - Prey_Tot_kg_Cons) %>%
  mutate(Ratio_kg_Cons = Prey_Tot_kg_Cons/Pre_Ratio_kg_Cons) %>%
  relocate(Num_Ind, Ind_Tot, Density, Density_Tot, Prop_Ind, Prop_Ind_Avail, Ratio_Ind, Pre_Ratio_Ind, Ratio_Ind_Avail, Prop_kg_Avail, Ratio_kg_Avail, Mass_Cat, Pantheria_kg, Avg_Mass_kg, .before = Orig_BM_Avail) %>%
  relocate(Prey_Tot_kg_Cons, Tot_kg_Cons, Prop_kg_Cons, Ratio_Occs, Ratio_kg_Cons, .before = Mean_Perc_Vol) %>%
  filter(!is.na(Prop_Ind)) %>%
  group_by(Study_Code, Period) %>%
  filter(n() >= 2) %>%
  ungroup() 
  

```

```{r}
#prep df for all wildlife model 
scatstudy.4den <- scatstudy %>%
  filter(!is.na(Prop_kg_Cons), !is.na(Prop_kg_Avail)) %>%
  filter(Prop_kg_Avail >= 0.01) %>%
    filter(Prop_kg_Cons >= 0.01) %>%
  mutate(Study_Code = as.factor(Study_Code),
    Prey_Taxa_Valid = as.factor(Prey_Taxa_Valid))# %>%
  # filter(Prey_Taxa_Valid %in%c("Sus scrofa", "Alces alces", "Capreolus capreolus", "Cervus elaphus", "Dama dama"))

###plot
ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Prey_Taxa_Valid), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Study_Country), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Ecoregion_OneEarth2), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Bioregion_OneEarth), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = n_Prey_Species), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Wild_Ung_Avail_n), alpha = 0.5)

ggplot(scatstudy.4den ) + geom_density(aes((Prop_kg_Cons), fill = Mass_Cat), alpha = 0.5)

####zero makes you get an output for each variable not reference in the intercept, otherwise don't worry about including

# model <- lmer(response ~ Variable1:Variable2 +(1|HigherLevelRandomEffect/LowerLevelRandomEffect) , data=datatable)
#do response ~ 0 + Variable1:Variable2 if either variable is categorical
# : is an interaction, * is another interaction, + is combined
# summary(model)

scatstudy.4mw <- scatstudy.4den  %>%
   mutate(
   n_Prey_Species = as.numeric(n_Prey_Species),
   Wild_Ung_Avail_n = as.numeric(Wild_Ung_Avail_n)
   )
                
```

```{r}
modelw.kga.pankg <- glm(Prop_kg_Cons ~ Prop_kg_Avail*Pantheria_kg, data= scatstudy.4mw)
summary(modelw.kga.pankg)

plot(modelw.kga.pankg)

confint(modelw.kga.pankg)
```

```{r}
modelw.kga.mc.wun.def.ecooe <- glm(Prop_kg_Cons ~ 0 + Prop_kg_Avail + Mass_Cat + Wild_Ung_Avail_n + Defense + Biome_Detal_Name, data= scatstudy.4mw) #Proportion biomass consumed ~ 0 + Proportion biomass available + body size category + number of wild ungulate prey species + antipredator + biome
summary(modelw.kga.mc.wun.def.ecooe)

#plot(modelw.kga.mc.wun.def.ecooe)

#confint(modelw.kga.mc.wun.def.ecooe)
```

```{r, #visualizing numeric predictors}

##Proportion biomass available##
eff.avail <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = "Prop_kg_Avail"
)
plot(eff.avail)

##Species of wild ungulate available##
eff.ungavailn <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = "Wild_Ung_Avail_n"
)
plot(eff.ungavailn)

##body mass category##
eff.kg <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = "Mass_Cat"
)
plot(eff.kg)


##Antipredator defense##
eff.defense <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = "Defense"
)
plot(eff.defense)

##OneEarth Ecoregion##
eff.biome <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = "Biome_Detal_Name"
)
plot(eff.biome)
```

```{r}
eff_interact <- ggpredict(
  modelw.kga.mc.wun.def.ecooe,
  terms = c("Prop_kg_Avail", "Mass_Cat"))


ggplot(eff_interact, aes(x = x, y = predicted, color = group)) +
  geom_line(size = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.2, color = NA) +
  labs(
    x = "Proportion of Biomass Available",
    y = "Predicted Proportion Biomass Consumed",
    color = "Mass Category",
    fill = "Mass Category"
  ) +
  theme_bw()
```

```{r}
coef_df <- tidy(modelw.kga.mc.wun.def.ecooe, conf.int = TRUE)

allcov <- ggplot(coef_df, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Coefficient estimate", y = "")
ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/allcov.png", plot = allcov, height = 5, width = 7, dpi = 700)
allcov
```

```{r}
scatstudy_cons_avail_plot <- ggplot(scatstudy) +
  geom_point(aes(x = Prop_kg_Avail, y = Prop_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
  scale_x_continuous(breaks = c(0, 0.5, 1)) +  
  scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Proportion of Biomass Available") + 
  ylab("Proportion of Biomass Consumed")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scatstudy_cons_avail_plot.png", plot = scatstudy_cons_avail_plot, height = 5, width = 7, dpi = 700)

scatstudy_cons_avail_plot
```

```{r}
scat.nomixedgroup <- scatstudy %>%
  filter(!Prey_Item %in% ("Cervids"))

scat.sus.1 <- scatstudy %>%
  group_by(Study_Code, Period) %>%
  filter(any(Prey_Taxa_Valid == "Sus scrofa")) %>%
  ungroup()
 # count(Prey_Taxa_Valid, sort = TRUE)
  
scat.sus <- scat.sus.1 %>%
  filter(Prey_Taxa_Valid %in% c("Sus scrofa", "Dama dama", "Alces alces", "Capreolus caprolus", "Cervus elaphus")) %>%
  group_by(Study_Code, Period) %>%
  filter(n() >= 2) %>%
  ungroup()
 # count(Prey_Taxa_Valid, sort = TRUE)

#prey2.combinations <- scattop2.nomixedgroup %>%
 # group_by(Study_Code, Period) %>%
 # summarise(
 #   Prey_Pair = paste(sort(Prey_Taxa_Valid), collapse = " + "),
  #  .groups = "drop"
 # ) %>%
 # count(Prey_Pair, sort = TRUE)

```


######################### TOP 2 WILD ONLY ####################
```{r}
scattop2abund.norecalc <- scatstudy %>%
filter(Ratio_kg_Cons > 0) %>%
  group_by(Study_Code, Period) %>%
  arrange(desc(Ratio_Ind)) %>%  
  slice_head(n = 2) #%>%  # Select the top 2 values for each group
#  group_by(Study_Code, Period) %>%
  #mutate(sum_top_two_kg_cons = sum(Prop_kg_Cons, na.rm = TRUE)) %>%  # Sum the top 2 values
 # ungroup() %>%
# filter(sum_top_two_kg_cons >= 0.70)   # Filter rows where cumulative sum reaches at least 0.70
 

scattop2abund <- scattop2abund.norecalc %>%
  mutate(Num_Ind = if_else(is.na(Num_Ind) & !is.na(Density) & !is.na(Area),
                            Density * Area, Num_Ind)) %>% 
  mutate(Density = if_else(is.na(Density) & !is.na(Num_Ind) & !is.na(Area),
                           Num_Ind / Area, Density)) %>%
group_by(Study_Code, Period) %>%
   mutate(Ind_Tot = sum(Num_Ind),
    Density_Tot = sum(Density),
    Prop_Ind_Avail_Sum = sum(Prop_Ind_Avail)) %>%
  ungroup() %>%
      # Proportion of individuals available
         mutate(Prop_Ind = case_when(
      is.na(Num_Ind) & !is.na(Prop_Ind_Avail) ~ Prop_Ind_Avail/Prop_Ind_Avail_Sum,
      !is.na(Num_Ind) & !is.na(Ind_Tot) ~ Num_Ind / Ind_Tot,
      !is.na(Density) & !is.na(Density_Tot) ~  Density / Density_Tot,
      TRUE ~ NA_real_
    ),
         # Ratio of individuals available
           Pre_Ratio_Ind = 1 - Prop_Ind,
    Ratio_Ind = Prop_Ind / Pre_Ratio_Ind,
  ) %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
 # Proportion of Pantheria kg available
   mutate(PropInd_x_Pan = Prop_Ind * Pantheria_kg) %>%
  ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Sum_PropInd_x_Pan = sum(PropInd_x_Pan)) %>%
  mutate(Prop_kg_Avail = PropInd_x_Pan / Sum_PropInd_x_Pan) %>%
 # Ratio of Pantheria kg available
  mutate(Pre_Ratio_kg_Avail = Sum_PropInd_x_Pan - PropInd_x_Pan) %>%
  mutate(Ratio_kg_Avail = PropInd_x_Pan / Pre_Ratio_kg_Avail) %>%
  #Step 2: Calculate the Scat_n_Prey, new relative FO, BM consumed, and ratio and prop of BM consumed
  #Make sure everything has a Scat_n_Prey if possible
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(Scat_n_Prey = ifelse(is.na(Scat_n_Prey), Scat_n_Tot*Abs_FO/100, Scat_n_Prey)) %>%
  ungroup() %>%
  #Calculate a new Relative_FO and a Ratio of Occurences
   group_by(Study_Code, Period) %>%
   mutate(Scat_items_Tot = sum(Scat_n_Prey)) %>%
    mutate(New_Rel_FO = Scat_n_Prey/Scat_items_Tot) %>%
    mutate(Pre_Ratio_Occ = Scat_items_Tot - Scat_n_Prey) %>%
    mutate(Ratio_Occs = Scat_n_Prey/Pre_Ratio_Occ) %>%
  #Calculate BM consumed (using (kg per scat)*Abs FO = 0.439+(0.008*Pan kg))
  mutate(Abs_FO = ifelse(is.na(Abs_FO), Scat_n_Prey/Scat_n_Tot, Abs_FO)) %>%
   mutate(kg_Per_Scat = 0.439+0.008*Pantheria_kg) %>%
#Calculate the proportion and ratio of biomass consumed
  mutate(Prey_Tot_kg_Cons = kg_Per_Scat*Scat_n_Prey) %>%
  mutate(Tot_kg_Cons = sum(Prey_Tot_kg_Cons)) %>%
  mutate(Prop_kg_Cons = Prey_Tot_kg_Cons/Tot_kg_Cons) %>%
  mutate(Pre_Ratio_kg_Cons = Tot_kg_Cons - Prey_Tot_kg_Cons) %>%
  mutate(Ratio_kg_Cons = Prey_Tot_kg_Cons/Pre_Ratio_kg_Cons) %>%
  relocate(Num_Ind, Ind_Tot, Density, Density_Tot, Prop_Ind, Prop_Ind_Avail, Ratio_Ind, Pre_Ratio_Ind, Ratio_Ind_Avail, Prop_kg_Avail, Ratio_kg_Avail, Mass_Cat, Pantheria_kg, Avg_Mass_kg, .before = Orig_BM_Avail) %>%
  relocate(Prey_Tot_kg_Cons, Tot_kg_Cons, Prop_kg_Cons, Ratio_Occs, Ratio_kg_Cons, .before = Mean_Perc_Vol) %>%
  filter(!is.na(Ratio_Ind),is.finite(Ratio_Ind), !Ratio_Ind %in% c(0, 1)) %>%
   group_by(Study_Code, Period) %>%
  filter(n() == 2) %>%
  ungroup()

scattop2abund.bysize <- scattop2abund %>%
  group_by(Study_Code, Period) %>%
  arrange(Pantheria_kg, .by_group = TRUE) %>%
   mutate(
    PreyX = if_else(row_number() == 1, "smaller", "larger")
  ) %>%
  ungroup()

scattop2abund.more <- scattop2abund %>%
  group_by(Study_Code, Period) %>%
  arrange(desc(Ratio_Ind), .by_group = TRUE) %>%
   mutate(
    PreyAbund = if_else(row_number() == 1, "More", "Fewer"),
    Prey_Pair = paste(sort(Prey_Taxa_Valid), collapse = " / ")
  ) %>%
  ungroup() %>%
   filter(PreyAbund == "More")

scattop2abund.morekg <- scattop2abund %>%
  group_by(Study_Code, Period) %>%
  arrange(desc(Ratio_kg_Cons), .by_group = TRUE) %>%
   mutate(
    PreykgAbund = if_else(row_number() == 1, "More", "Fewer"),
    Prey_Pair = paste(sort(Prey_Taxa_Valid), collapse = " + ")
  ) %>%
  ungroup() %>%
   filter(PreykgAbund == "More")

scattop2abund.nomixedgroup <- scattop2abund %>%
  filter(!Prey_Item %in% ("Cervids")) %>%
   group_by(Study_Code, Period) %>%
  filter(n() == 2) %>%
  ungroup()



scattop2kgabund.norecalc <- scatstudy %>%
filter(Ratio_kg_Cons > 0) %>%
  group_by(Study_Code, Period) %>%
  arrange(desc(Num_Ind)) %>%  
  slice_head(n = 2) #%>%  # Select the top 2 values for each group
#  group_by(Study_Code, Period) %>%
  #mutate(sum_top_two_kg_cons = sum(Prop_kg_Cons, na.rm = TRUE)) %>%  # Sum the top 2 values
 # ungroup() %>%
# filter(sum_top_two_kg_cons >= 0.70)   # Filter rows where cumulative sum reaches at least 0.70
 

scattop2kgabund <- scattop2kgabund.norecalc %>%
  mutate(Num_Ind = if_else(is.na(Num_Ind) & !is.na(Density) & !is.na(Area),
                            Density * Area, Num_Ind)) %>% 
  mutate(Density = if_else(is.na(Density) & !is.na(Num_Ind) & !is.na(Area),
                           Num_Ind / Area, Density)) %>%
group_by(Study_Code, Period) %>%
   mutate(Ind_Tot = sum(Num_Ind),
    Density_Tot = sum(Density),
    Prop_Ind_Avail_Sum = sum(Prop_Ind_Avail)) %>%
  ungroup() %>%
      # Proportion of individuals available
         mutate(Prop_Ind = case_when(
      is.na(Num_Ind) & !is.na(Prop_Ind_Avail) ~ Prop_Ind_Avail/Prop_Ind_Avail_Sum,
      !is.na(Num_Ind) & !is.na(Ind_Tot) ~ Num_Ind / Ind_Tot,
      !is.na(Density) & !is.na(Density_Tot) ~  Density / Density_Tot,
      TRUE ~ NA_real_
    ),
         # Ratio of individuals available
           Pre_Ratio_Ind = 1 - Prop_Ind,
    Ratio_Ind = Prop_Ind / Pre_Ratio_Ind,
  ) %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
 # Proportion of Pantheria kg available
   mutate(PropInd_x_Pan = Prop_Ind * Pantheria_kg) %>%
  ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Sum_PropInd_x_Pan = sum(PropInd_x_Pan)) %>%
  mutate(Prop_kg_Avail = PropInd_x_Pan / Sum_PropInd_x_Pan) %>%
 # Ratio of Pantheria kg available
  mutate(Pre_Ratio_kg_Avail = Sum_PropInd_x_Pan - PropInd_x_Pan) %>%
  mutate(Ratio_kg_Avail = PropInd_x_Pan / Pre_Ratio_kg_Avail) %>%
  #Step 2: Calculate the Scat_n_Prey, new relative FO, BM consumed, and ratio and prop of BM consumed
  #Make sure everything has a Scat_n_Prey if possible
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(Scat_n_Prey = ifelse(is.na(Scat_n_Prey), Scat_n_Tot*Abs_FO/100, Scat_n_Prey)) %>%
  ungroup() %>%
  #Calculate a new Relative_FO and a Ratio of Occurences
   group_by(Study_Code, Period) %>%
   mutate(Scat_items_Tot = sum(Scat_n_Prey)) %>%
    mutate(New_Rel_FO = Scat_n_Prey/Scat_items_Tot) %>%
    mutate(Pre_Ratio_Occ = Scat_items_Tot - Scat_n_Prey) %>%
    mutate(Ratio_Occs = Scat_n_Prey/Pre_Ratio_Occ) %>%
  #Calculate BM consumed (using (kg per scat)*Abs FO = 0.439+(0.008*Pan kg))
  mutate(Abs_FO = ifelse(is.na(Abs_FO), Scat_n_Prey/Scat_n_Tot, Abs_FO)) %>%
   mutate(kg_Per_Scat = 0.439+0.008*Pantheria_kg) %>%
#Calculate the proportion and ratio of biomass consumed
  mutate(Prey_Tot_kg_Cons = kg_Per_Scat*Scat_n_Prey) %>%
  mutate(Tot_kg_Cons = sum(Prey_Tot_kg_Cons)) %>%
  mutate(Prop_kg_Cons = Prey_Tot_kg_Cons/Tot_kg_Cons) %>%
  mutate(Pre_Ratio_kg_Cons = Tot_kg_Cons - Prey_Tot_kg_Cons) %>%
  mutate(Ratio_kg_Cons = Prey_Tot_kg_Cons/Pre_Ratio_kg_Cons) %>%
  relocate(Num_Ind, Ind_Tot, Density, Density_Tot, Prop_Ind, Prop_Ind_Avail, Ratio_Ind, Pre_Ratio_Ind, Ratio_Ind_Avail, Prop_kg_Avail, Ratio_kg_Avail, Mass_Cat, Pantheria_kg, Avg_Mass_kg, .before = Orig_BM_Avail) %>%
  relocate(Prey_Tot_kg_Cons, Tot_kg_Cons, Prop_kg_Cons, Ratio_Occs, Ratio_kg_Cons, Pre_Ratio_kg_Cons, .before = Mean_Perc_Vol) %>%
  filter(!is.na(Ratio_Ind),is.finite(Ratio_Ind), !Ratio_Ind %in% c(0, 1)) %>%
   group_by(Study_Code, Period) %>%
  filter(n() == 2) %>%
  ungroup()

scattop2kgabund.bysize <- scattop2kgabund %>%
  group_by(Study_Code, Period) %>%
  arrange(Pantheria_kg, .by_group = TRUE) %>%
   mutate(
    PreyX = if_else(row_number() == 1, "smaller", "larger")
  ) %>%
  ungroup()

scattop2kgabund.more <- scattop2kgabund %>%
  group_by(Study_Code, Period) %>%
  arrange(desc(Ratio_kg_Cons), .by_group = TRUE) %>%
   mutate(
    PreykgAbund = if_else(row_number() == 1, "More", "Fewer")
  ) %>%
  ungroup() %>%
   filter(PreykgAbund == "More")


scattop2kgabund.nomixedgroup <- scattop2kgabund %>%
  filter(!Prey_Item %in% ("Cervids")) %>%
   group_by(Study_Code, Period) %>%
  filter(n() == 2) %>%
  ungroup()

```

```{r, #top 2 portion}
modelw.scattop2 <- glm(Prop_kg_Cons ~ 0 + Prop_kg_Avail + Mass_Cat +  Defense + Biome_Detal_Name, data= scattop2) #Proportion biomass consumed ~ 0 + Proportion biomass available + body size category +  antipredator + biome
summary(modelw.scattop2)
```

```{r, #top 2 portion}
coef_df2 <- tidy(modelw.scattop2, conf.int = TRUE)

allcov2 <- ggplot(coef_df2, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Coefficient estimate", y = "")
ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/allcov2.png", plot = allcov2, height = 5, width = 7, dpi = 700)
allcov2
```

```{r, #top 2 portion}
scattop2_cons_avail_plot <- ggplot(scattop2) +
  geom_point(aes(x = Prop_kg_Avail, y = Prop_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
  scale_x_continuous(breaks = c(0, 0.5, 1)) +  
  scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Proportion of Biomass Available") + 
  ylab("Proportion of Biomass Consumed")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_cons_avail_plot.png", plot = scattop2_cons_avail_plot, height = 5, width = 7, dpi = 700)

scattop2_cons_avail_plot
```

```{r}
scattop2_ratio_ind_occs_plot_all <- ggplot(scattop2) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Relative Availability") + 
  ylab("Relative Consumption")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_ratio_ind_occs_plot_all.png", plot = scattop2_ratio_ind_occs_plot_all, height = 5, width = 7, dpi = 700)

scattop2_ratio_ind_occs_plot_all
```


```{r, #ratio ind to occurrences}
modelw.ratio.ind.occ.scattop2.all <- glm(Ratio_Occs ~ 0 + Ratio_Ind + Mass_Cat +  Defense + Biome_Detal_Name, data= scattop2) #ratio of occurences in scat (occurence prey 1/occurence prey 2) ~ 0 + ratio of ind available (prey 1/prey 2) + body size category +  antipredator + biome
summary(modelw.ratio.ind.occ.scattop2.all)
```

```{r}
coef_df3 <- tidy(modelw.ratio.ind.occ.scattop2.all, conf.int = TRUE)

cov3 <- ggplot(coef_df3, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Coefficient estimate", y = "")
ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/cov3.png", plot = cov3, height = 5, width = 7, dpi = 700)
cov3
```


```{r, #Ratios ind to occurences, no extremes}
scattop2.noextremes <- scattop2 %>%
  filter(Ratio_Occs < 12) %>%
   filter(Ratio_Ind < 12)

scattop2_ratio_ind_occs_plot <- ggplot(scattop2.noextremes) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Relative Availability") + 
  ylab("Relative Consumption")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_ratio_ind_occs_plot.png", plot = scattop2_ratio_ind_occs_plot, height = 5, width = 7, dpi = 700)

scattop2_ratio_ind_occs_plot
```

```{r}
modelw.ratio.ind.occ.scattop2.noextremes <- glm(Ratio_Occs ~ 0 + Ratio_Ind + Mass_Cat +  Defense + Biome_Detal_Name, data= scattop2.noextremes) #ratio of occurences in scat (occurence prey 1/occurence prey 2) ~ 0 + ratio of ind available (prey 1/prey 2) + body size category +  antipredator + biome
summary(modelw.ratio.ind.occ.scattop2.noextremes)
```

```{r}
coef_df4 <- tidy(modelw.ratio.ind.occ.scattop2.noextremes, conf.int = TRUE)

cov4 <- ggplot(coef_df4, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Coefficient estimate", y = "")
ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/cov4.png", plot = cov4, height = 5, width = 7, dpi = 700)
cov4
```

```{r}
scattop2.bysize <- scattop2.bysize %>%
  filter(Ratio_Occs < 12) %>%
   filter(Ratio_Ind < 12)

scattop2_ratio_bysize_plot <- ggplot(scattop2.bysize) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs, color = Prey_Taxa_Valid)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Relative Availability") + 
  ylab("Relative Consumption")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_ratio_ind_occs_plot_bysize.png", plot = scattop2_ratio_bysize_plot, height = 5, width = 7, dpi = 700)

scattop2_ratio_bysize_plot
```

```{r}
modelw.scattop2.abund <- glm(Ratio_Occs ~ 0 + Ratio_Ind + Mass_Cat +  Defense + Biome_Detal_Name, data= scattop2.abund) #Proportion biomass consumed ~ 0 + Proportion biomass available + body size category +  antipredator + biome
summary(modelw.scattop2.abund)
```

```{r}
#scattop2abund.more %>%
#  count(Prey_Pair, sort = TRUE)

scattop2abund_more_preypair <- ggplot(scattop2abund.more) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs, color = Prey_Pair)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12)) +  
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8)) +  

  scale_color_viridis_d(
    option = "turbo",
    name = "Prey1/Prey2"
  ) +
  
  xlab("Relative Abundance Prey1/Prey2") + 
  ylab("Relative Consumption Prey1/Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2abund_more_preypair.png", plot = scattop2abund_more_preypair, height = 5, width = 7, dpi = 700)

scattop2abund_more_preypair



scattop2abund_more_studycode <- ggplot(scattop2abund.more) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs, color = Study_Code)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12)) +  
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8)) +  

  scale_color_viridis_d(
    option = "turbo",
    name = "Study Code"
  ) +
  
  xlab("Relative Abundance Prey1/Prey2") + 
  ylab("Relative Consumption Prey1/Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2abund_more_studycode.png", plot = scattop2abund_more_studycode, height = 5, width = 7, dpi = 700)

scattop2abund_more_studycode



scattop2abund_more_PaperID <- ggplot(scattop2abund.more) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs, color = Paper_ID)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12)) +  
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8)) +  

  scale_color_viridis_d(
    option = "turbo",
    name = "Study ID"
  ) +
  
  xlab("Relative Abundance Prey1/Prey2") + 
  ylab("Relative Consumption Prey1/Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2abund_more_PaperID.png", plot = scattop2abund_more_PaperID, height = 5, width = 7, dpi = 700)

scattop2abund_more_PaperID




scattop2abund.more.density <- scattop2abund.more %>%
  filter(!is.na(Density))

scattop2abund_more_density <- ggplot(scattop2abund.more.density) +
  geom_point(aes(x = Ratio_Ind, y = Ratio_Occs, color = Density)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12)) +  
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8)) +  

  scale_color_viridis_c(
    option = "plasma", begin = 0.1, end = 0.95, trans = "log10",
    name = "Prey1 Density"
  ) +
  
  xlab("Relative Abundance Prey1/Prey2") + 
  ylab("Relative Consumption Prey1/Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2abund_more_density.png", plot = scattop2abund_more_density, height = 5, width = 7, dpi = 700)

scattop2abund_more_density
```




```{r}
scattop2kgabund_more <- ggplot(scattop2kgabund.more) +
  geom_point(aes(x = Ratio_kg_Avail, y = Ratio_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Relative kg Abundance Prey1/Prey2") + 
  ylab("Relative kg Consumption Prey1/Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2kgabund_more.png", plot = scattop2kgabund_more, height = 5, width = 7, dpi = 700)

scattop2kgabund_more
```


```{r}
scattop2.wildboar <- scattop2.noextremes%>%
  filter(Prey_Taxa_Valid == "Sus scrofa")

scattop2_ratio_wildboar <- ggplot(scattop2.wildboar) +
  geom_point(aes(x = Ratio_kg_Avail, y = Ratio_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Avail. kg Wild Boar/Avail. kg Prey2") + 
  ylab("Cons. kg Wild Boar/Cons. kg Prey2")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_ratio_wildboar.png", plot = scattop2_ratio_wildboar, height = 5, width = 7, dpi = 700)

scattop2_ratio_wildboar
```

```{r}
scat.boar.elk <- scattop2.noextremes%>%
  filter(Prey_Taxa_Valid %in% c("Sus scrofa", "Cervus elaphus")) %>%
  group_by(Study_Code, Period) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  filter(Prey_Taxa_Valid %in% c("Sus scrofa"))

scat_boar_elk <- ggplot(scat.boar.elk) +
  geom_point(aes(x = Ratio_kg_Avail, y = Ratio_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Relative kg Available") + 
  ylab("Relative kg Consumed")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scat_boar_elk.png", plot = scat_boar_elk, height = 5, width = 7, dpi = 700)

scat_boar_elk
```


```{r, #ratios kg}
modelw.ratio.kg.scattop2.noextremes <- glm(Ratio_kg_Cons ~ 0 + Ratio_kg_Avail + Mass_Cat +  Defense + Biome_Detal_Name, data= scattop2.noextremes) #ratio biomass consumed ~ 0 + ratio biomass available + body size category +  antipredator + biome
summary(modelw.ratio.kg.scattop2.noextremes)
```

```{r}
coef_df5 <- tidy(modelw.ratio.kg.scattop2.noextremes, conf.int = TRUE)

cov5 <- ggplot(coef_df5, aes(x = estimate, y = term)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Coefficient estimate", y = "")
ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/cov5.png", plot = cov4, height = 5, width = 7, dpi = 700)
cov5
```


```{r}
scattop2_ratio_kg_plot <- ggplot(scattop2) +
  geom_point(aes(x = Ratio_kg_Avail, y = Ratio_kg_Cons)) + 
  geom_abline(intercept = 0, slope = 1, linetype = "dashed") + 
  theme_classic() + 
  theme(text = element_text(size = 10)) +
  
  # Reduce the number of ticks on the axes
 # scale_x_continuous(breaks = c(0, 0.5, 1)) +  
 # scale_y_continuous(breaks = c(0, 0.5, 1)) +  
  
  xlab("Ratio of Biomass Available") + 
  ylab("Ratio of Biomass Consumed")

ggsave("~/Github/preyswitch_litrev/WIP - Report Stage 2/plots/scattop2_ratio_kg_plot.png", plot = scattop2_ratio_kg_plot, height = 5, width = 7, dpi = 700)

scattop2_ratio_kg_plot
```

```{r}

```


#################################################################

```{r}
scatpref.unfinished <- ScatPref_Nov2025 %>%
  select(Study_Code, Paper_ID, Study_Area, Area, Prey_Item, Prey_Taxa_Valid, Period, Num_Ind, Ratio_Ind_Avail, Prop_Ind_Avail, Density, Avg_Mass_kg, Pantheria_kg, Orig_BM_Avail, Orig_Prop_BM_Avail, Scat_n_Tot, Scat_n_Prey, Abs_FO, Rel_FO, Mean_Perc_Vol, Orig_BM_Consumed, Orig_Prop_BM_Consumed, Livestock_Wild, Defense, n_Prey_Species, Wild_Ung_Avail_n) %>%
  filter(!Livestock_Wild %in%c("Feral", "Livestock")) %>%
  group_by(Study_Code, Period) %>%
  filter(n() >= 2) %>%
  ungroup() 

killpref.unfinished <- KillPref_Nov2025 %>%
  filter(!Livestock_Wild %in%c("Feral", "Livestock")) %>%
  group_by(Study_Code, Period) %>%
  filter(n() >= 2) %>%
  ungroup() 


scatpref <- scatstudy.unfinished %>%
  mutate(Num_Ind = if_else(is.na(Num_Ind) & !is.na(Density) & !is.na(Area),
                            Density * Area, Num_Ind)) %>% 
  mutate(Density = if_else(is.na(Density) & !is.na(Num_Ind) & !is.na(Area),
                           Num_Ind / Area, Density)) %>%
group_by(Study_Code, Period) %>%
   mutate(Ind_Tot = sum(Num_Ind),
    Density_Tot = sum(Density),
    Prop_Ind_Avail_Sum = sum(Prop_Ind_Avail)) %>%
  ungroup() %>%
         # Proportion of individuals available
         mutate(Prop_Ind = ifelse(is.na(Num_Ind), Prop_Ind_Avail/Prop_Ind_Avail_Sum, ifelse(!is.na(Num_Ind) & Ind_Tot>0, Num_Ind / Ind_Tot, NA_real_)),
         # Ratio of individuals available
         Pre_Ratio_Ind = ifelse(is.na(Num_Ind), 1 - Prop_Ind, ifelse(!is.na(Num_Ind) & !is.na(Ind_Tot), Ind_Tot - Num_Ind, NA_real_)),
         Ratio_Ind = ifelse(is.na(Num_Ind), ifelse(!is.na(Prop_Ind) & !is.na(Pre_Ratio_Ind), Prop_Ind / Pre_Ratio_Ind, NA_real_),
                            ifelse(!is.na(Num_Ind) & !is.na(Pre_Ratio_Ind) & Pre_Ratio_Ind>0, Num_Ind / Pre_Ratio_Ind, NA_real_))
  ) %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
 # Proportion of Pantheria kg available
   mutate(PropInd_x_Pan = Prop_Ind * Pantheria_kg) %>%
  ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Sum_PropInd_x_Pan = sum(PropInd_x_Pan)) %>%
  mutate(Prop_kg_Avail = PropInd_x_Pan / Sum_PropInd_x_Pan) %>%
 # Ratio of Pantheria kg available
  mutate(Pre_Ratio_kg_Avail = Sum_PropInd_x_Pan - PropInd_x_Pan) %>%
  mutate(Ratio_kg_Avail = PropInd_x_Pan / Pre_Ratio_kg_Avail) %>%
  #Step 2: Calculate the Scat_n_Prey, new relative FO, BM consumed, and ratio and prop of BM consumed
  #Make sure everything has a Scat_n_Prey if possible
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(Scat_n_Prey = ifelse(is.na(Scat_n_Prey), Scat_n_Tot*Abs_FO/100, Scat_n_Prey)) %>%
  ungroup() %>%
  #Calculate a new Relative_FO and a Ratio of Occurences
   group_by(Study_Code, Period) %>%
   mutate(Scat_items_Tot = sum(Scat_n_Prey)) %>%
    mutate(New_Rel_FO = Scat_n_Prey/Scat_items_Tot) %>%
    mutate(Pre_Ratio_Occ = Scat_items_Tot - Scat_n_Prey) %>%
    mutate(Ratio_Occs = Scat_n_Prey/Pre_Ratio_Occ) %>%
  #Calculate BM consumed (using (kg per scat)*Abs FO = 0.439+(0.008*Pan kg))
  mutate(Abs_FO = ifelse(is.na(Abs_FO), Scat_n_Prey/Scat_n_Tot, Abs_FO)) %>%
   mutate(kg_Per_Scat = 0.439+0.008*Pantheria_kg) %>%
#Calculate the proportion and ratio of biomass consumed
  mutate(Prey_Tot_kg_Cons = kg_Per_Scat*Scat_n_Prey) %>%
  mutate(Tot_kg_Cons = sum(Prey_Tot_kg_Cons)) %>%
  mutate(Prop_kg_Cons = Prey_Tot_kg_Cons/Tot_kg_Cons) %>%
  mutate(Pre_Ratio_kg_Cons = Tot_kg_Cons - Prey_Tot_kg_Cons) %>%
  mutate(Ratio_kg_Cons = Prey_Tot_kg_Cons/Pre_Ratio_kg_Cons) %>%
  relocate(Mass_Cat, Ind_Tot, Density_Tot, Prop_Ind, Prop_kg_Avail, Ratio_kg_Avail, .before = Orig_BM_Avail) %>%
  relocate(Prey_Tot_kg_Cons, Tot_kg_Cons, Prop_kg_Cons, Ratio_kg_Cons, .before = Mean_Perc_Vol)

########## kill data
killpref <- killpref.unfinished %>%
  # make sure everything that needs to be numeric is numeric
   mutate(
    Num_Ind = as.numeric(Num_Ind),
    Area = as.numeric(Area),
    Prop_Ind_Avail = as.numeric(Prop_Ind_Avail),
    Ratio_Ind_Avail = as.numeric(Ratio_Ind_Avail)
  )  %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(Density = ifelse(is.na(Density), Num_Ind/Area, Density))      %>%
    ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Abs_Density = sum(Density)) %>%
    ungroup() %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
    mutate(Prop_Ind_Avail = ifelse(is.na(Prop_Ind_Avail),               Density/Abs_Density, Prop_Ind_Avail)) %>%
    ungroup() %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
   mutate(n_Kills_Prey = ifelse(is.na(n_Kills_Prey),                    n_Kills_Tot*Prop_Kills, n_Kills_Prey)) %>%
    ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(New_n_Kills_Tot = sum(n_Kills_Prey)) %>%
    ungroup() %>%
  group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
    mutate(New_Prop_Kill =  n_Kills_Prey/New_n_Kills_Tot) %>%
    mutate(Kill_kg_Prey = n_Kills_Prey*Pantheria_kg) %>%
    ungroup() %>%
  group_by(Study_Code, Period) %>%
   mutate(Kill_kg_Tot = sum(Kill_kg_Prey)) %>%
    ungroup() %>%
   group_by(Study_Code, Period, Prey_Taxa_Valid) %>%
    mutate(Kill_Prop_kg_Cons = Kill_kg_Prey/Kill_kg_Tot) %>%
    mutate(Prop_kg_Cons = Kill_Prop_kg_Cons) %>%
    ungroup()

scatpref.tocombine <- scatpref %>%
  select(Study_Code, Period, Area, Prey_Taxa_Valid, Num_Ind, Prop_kg_Avail, Density,  Pantheria_kg, Prop_kg_Cons)
killpref.tocombine <- killpref %>%
  select(Study_Code, Period, Area, Prey_Taxa_Valid, Prop_kg_Avail, Density, Pantheria_kg, Prop_kg_Cons)
allpref <- bind_rows(scatpref.tocombine, killpref.tocombine) %>%
  distinct(Study_Code, Period, .keep_all = TRUE)

allprefstudy <- allpref.unfinished %>%
  left_join(studyarea, by = "Study_Code")

allprefstudy$Mass_Cat <- cut(allprefstudy$Pantheria_kg,
                                     breaks = c(0, 20.5, 80.5, 150.5, 300.5, 500.5, Inf),  
                                     labels = c("≤ 20 kg", "20-80 kg", "80-150 kg", "150-300 kg", "300-500 kg", "≥ 500 kg"), 
                                     right = FALSE) # Use right=FALSE for inclusive lower bounds

```

